### ISSUE TITLE
Can pair-based RF models be used to predict on pseudobulk samples and individual cells?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/medulloblastoma-classifier#66]
@envest and I can not remember if we tried using RF models to predict subtypes for pseudobulk samples and individual cells. #50 is undoubtedly looking at kTSP models. RF models, with the right arguments, can return probabilities, which some may find appealing!

**Comment by envest** [comment]
Yes, RF models can be used on pseudobulk and individual cells. LASSO and MM2S could not be used (generally) on single cell data because of model features not being present in single cell data.

We did use RF models to predict subgroup using pseudobulk sample and individual cells, but we only visualized/analyzed results based on the kTSP model. I expect we did look at RF results at some point but now I can't recall why that analysis was set aside. Definitely something to come back to.
